# Uncomment the next line to define a global platform for your project
# platform :ios, '17.3'

target 'BookHarbour' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookHarbour
	source 'https://github.com/readium/podspecs'
	source 'https://cdn.cocoapods.org/'

	pod 'ReadiumShared', '~> 3.1.0'
	pod 'ReadiumStreamer', '~> 3.1.0'
	pod 'ReadiumNavigator', '~> 3.1.0'
	pod 'ReadiumOPDS', '~> 3.1.0'
	pod 'ReadiumLCP', '~> 3.1.0'
	pod 'ReadiumAdapterGCDWebServer', '~> 3.1.0'

end
